### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by seductorAmadeus** [IoannTar2004/laba5#1]
- https://github.com/IoannTar2004/laba5/blob/f5123b05916624175de9ef3245a8de163fba3628/src/tools/IdGenerator.java#L19
https://github.com/IoannTar2004/laba5/blob/f5123b05916624175de9ef3245a8de163fba3628/src/tools/IdGenerator.java#L15

- https://github.com/IoannTar2004/laba5/blob/f5123b05916624175de9ef3245a8de163fba3628/src/tools/ScriptReader.java#L29

- https://github.com/IoannTar2004/laba5/blob/f5123b05916624175de9ef3245a8de163fba3628/src/tools/ScriptReader.java#L25

- Вероятно переписать https://github.com/IoannTar2004/laba5/blob/master/src/tools/XMLReader.java

- https://github.com/IoannTar2004/laba5/blob/master/src/collectionClasses/CollectionManager.java - статики выкинуть
-https://github.com/IoannTar2004/laba5/blob/f5123b05916624175de9ef3245a8de163fba3628/src/commands/UpdateIdCommand.java#LL19C34-L19C43 

- https://github.com/IoannTar2004/laba5/blob/f5123b05916624175de9ef3245a8de163fba3628/src/commands/UpdateIdCommand.java#L36-L118

**Comment by seductorAmadeus** [comment]
<img width="856" alt="image" src="https://user-images.githubusercontent.com/18173541/225575944-cf6ff0e3-d03b-47eb-8c62-896053e80e79.png">

**Comment by seductorAmadeus** [comment]
пустой файл

**Comment by seductorAmadeus** [comment]
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/18173541/225578164-f5c21e70-e877-4f6f-b4e9-e270ee96c8e8.png">

**Comment by seductorAmadeus** [comment]
<root>
 	<object id = 274726478289>
		<name>Ivan</name>
		<coordinates>55; 746</coordinates>
		<age>3</age>
		<color>Чёрный</color>
		<type>Воздушный</type>
		<character>Злой</character>
		<cavedepth>3.04</cavedepth>
	</object>

 	<object id = "274726478289">
		<name>Ivan</name>
		<coordinates>55; 746</coordinates>
		<age>3</age>
		<color>Чёрный</color>
		<type>Воздушный</type>
		<character>Злой</character>
		<cavedepth>3.04</cavedepth>
	</object>
</root>


1 невалидный объект из двух, считывает только один

**Comment by seductorAmadeus** [comment]
~

**Comment by seductorAmadeus** [comment]
field.equals("1")

**Comment by IoannTar2004** [comment]
Все исправлено
